#pragma once

#define SIDEBARREF_TITLE " your games "
#define SIDEBARREF_IS_ALIGN FC_ALIGN_CENTER
#define SIDEBARREF_BORDER_DESIGN FC_BORDER_SINGLE

#define SEARCHBTN_TEXT_IS_ALIGN FC_ALIGN_LEFT
#define SEARCHBTN_TEXT "search games"
